/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayManagement;



import BarangayManagement.ResidentProfile;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Date;
import com.mysql.jdbc.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Jay Tanza
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Color DefaultColor,ClickedColor;
    public Dashboard() {
        initComponents();
        DefaultColor= new Color(21,25,28);
        ClickedColor= new Color(62,67,76);
        
        jPanel4.setBackground(DefaultColor);
        jPanel5.setBackground(DefaultColor);
        jPanel6.setBackground(DefaultColor);
        jPanel3.setBackground(DefaultColor);
        jPanel8.setBackground(DefaultColor);
        //jPanel7.setBackground(DefaultColor);
        //jLabel_image.setVisible(false);
        showTime();
        showDate();
        showTable();
        setIconImage();
        

        //LoginAs.setVisible(false);
        //LoginAs.setText(LoginAs);
    }
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("mactanlogo.png")));
    }
   public void showTable() 
    {

       try {
        String sql = "SELECT Fullname FROM `useraccountinfo` WHERE Fullname = ?";
        pst = MyConnection.getConnection().prepareStatement(sql);
        pst.setString(1,Displayname2.getText());
        rs = pst.executeQuery();
        if(rs.next())
            {
              //jTextField_answer.setText(rs.getString("Answer"));
              String Fullname = rs.getString("Fullname");
              Displayname2.setText(Fullname);
            }
       
       }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
    }
        void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM/dd/yyyy");
        lblDate2.setText("Date: " + s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        lblTime2.setText("Time: " + s.format(d));
            }
            
        }
        ).start();
    }

    void report(){
        Connection con=null;
        String report = "INSERT INTO `audittrail`(`Date`, `Time`) VALUES (?,?)";
            Date d = new Date();       
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat c = new SimpleDateFormat("hh:mm:ss");
            String date = (s.format(d));
            String time = (c.format(d));
    try{
            pst = MyConnection.getConnection().prepareStatement(report);
            //pst = MyConnection.getConnection().prepareStatement(report2); //jTextField_Username
            pst.setString(1, date);
            pst.setString(2, time);
            
            pst.executeUpdate();
            }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        lblDate2 = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        Firstname = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        Middlename = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Phonenumber = new javax.swing.JTextField();
        jLabel_Image = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Displayname2 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 33)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("AND INFORMATION SYSTEM");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 420, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 33)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("BARANGAY MACTAN MANAGEMENT");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 540, 40));

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(995, 692));

        jPanel9.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images2/ahong cover1.jpg"))); // NOI18N

        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(433, 433, 433)
                .addComponent(jRadioButton6)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton7)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton8)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton9)
                .addGap(6, 6, 6)
                .addComponent(jRadioButton10)
                .addContainerGap(441, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(645, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jDesktopPane1.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 990, 670));

        lblDate2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate2.setForeground(new java.awt.Color(169, 224, 49));
        lblDate2.setText("Date");
        jPanel2.add(lblDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, -1));

        lblTime2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTime2.setForeground(new java.awt.Color(169, 224, 49));
        lblTime2.setText("Time");
        jPanel2.add(lblTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        Gender.setEditable(false);
        Gender.setBackground(new java.awt.Color(31, 36, 42));
        Gender.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Gender.setForeground(new java.awt.Color(31, 36, 42));
        Gender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Gender.setBorder(null);
        Gender.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GenderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                GenderFocusLost(evt);
            }
        });
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        Gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                GenderKeyPressed(evt);
            }
        });
        jPanel2.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, 40, 20));

        Firstname.setEditable(false);
        Firstname.setBackground(new java.awt.Color(31, 36, 42));
        Firstname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Firstname.setForeground(new java.awt.Color(31, 36, 42));
        Firstname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Firstname.setBorder(null);
        Firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstnameFocusLost(evt);
            }
        });
        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });
        Firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FirstnameKeyPressed(evt);
            }
        });
        jPanel2.add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 40, 20));

        Lastname.setEditable(false);
        Lastname.setBackground(new java.awt.Color(31, 36, 42));
        Lastname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Lastname.setForeground(new java.awt.Color(31, 36, 42));
        Lastname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lastname.setBorder(null);
        Lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastnameFocusLost(evt);
            }
        });
        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });
        Lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LastnameKeyPressed(evt);
            }
        });
        jPanel2.add(Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 40, 20));

        Middlename.setEditable(false);
        Middlename.setBackground(new java.awt.Color(31, 36, 42));
        Middlename.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Middlename.setForeground(new java.awt.Color(31, 36, 42));
        Middlename.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Middlename.setBorder(null);
        Middlename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MiddlenameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MiddlenameFocusLost(evt);
            }
        });
        Middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddlenameActionPerformed(evt);
            }
        });
        Middlename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MiddlenameKeyPressed(evt);
            }
        });
        jPanel2.add(Middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 40, 20));

        DOB.setEditable(false);
        DOB.setBackground(new java.awt.Color(31, 36, 42));
        DOB.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        DOB.setForeground(new java.awt.Color(31, 36, 42));
        DOB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DOB.setBorder(null);
        DOB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBFocusLost(evt);
            }
        });
        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        DOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DOBKeyPressed(evt);
            }
        });
        jPanel2.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, 40, 20));

        Age.setEditable(false);
        Age.setBackground(new java.awt.Color(31, 36, 42));
        Age.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Age.setForeground(new java.awt.Color(31, 36, 42));
        Age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Age.setBorder(null);
        Age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AgeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AgeFocusLost(evt);
            }
        });
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeKeyPressed(evt);
            }
        });
        jPanel2.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, 40, 20));

        Address.setEditable(false);
        Address.setBackground(new java.awt.Color(31, 36, 42));
        Address.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Address.setForeground(new java.awt.Color(31, 36, 42));
        Address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Address.setBorder(null);
        Address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AddressFocusLost(evt);
            }
        });
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AddressKeyPressed(evt);
            }
        });
        jPanel2.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 40, 20));

        ID.setEditable(false);
        ID.setBackground(new java.awt.Color(31, 36, 42));
        ID.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        ID.setForeground(new java.awt.Color(31, 36, 42));
        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ID.setBorder(null);
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IDKeyPressed(evt);
            }
        });
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 40, 20));

        Phonenumber.setEditable(false);
        Phonenumber.setBackground(new java.awt.Color(31, 36, 42));
        Phonenumber.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Phonenumber.setForeground(new java.awt.Color(31, 36, 42));
        Phonenumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Phonenumber.setBorder(null);
        Phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PhonenumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PhonenumberFocusLost(evt);
            }
        });
        Phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhonenumberActionPerformed(evt);
            }
        });
        Phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PhonenumberKeyPressed(evt);
            }
        });
        jPanel2.add(Phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, 40, 20));
        jPanel2.add(jLabel_Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 37, -1));
        jPanel2.add(jLabel_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 210));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1030, 800));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mactanlogo.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 130));

        jPanel3.setBackground(new java.awt.Color(21, 25, 28));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(169, 224, 49));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reports32.png"))); // NOI18N
        jLabel19.setText(" REPORTS/COMPLAINTS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 270, 60));

        jPanel4.setBackground(new java.awt.Color(21, 25, 28));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(169, 224, 49));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home32.png"))); // NOI18N
        jLabel26.setText("  DASHBOARD");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 270, 60));

        jPanel5.setBackground(new java.awt.Color(21, 25, 28));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(169, 224, 49));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/documents32.png"))); // NOI18N
        jLabel24.setText(" DOCUMENTS/REQUEST");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 270, -1));

        jPanel6.setBackground(new java.awt.Color(21, 25, 28));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(169, 224, 49));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/residents32#2.png"))); // NOI18N
        jLabel23.setText(" OFFICIALS RECORDS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 270, 60));

        jLabel8.setBackground(new java.awt.Color(169, 224, 49));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Minus_32px_1.png"))); // NOI18N
        jLabel8.setText("Log-Out");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, -1, 38));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("LOG-IN AS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 80, -1));

        Displayname2.setEditable(false);
        Displayname2.setBackground(new java.awt.Color(21, 25, 28));
        Displayname2.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        Displayname2.setForeground(new java.awt.Color(255, 255, 255));
        Displayname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Displayname2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        Displayname2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Displayname2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Displayname2FocusLost(evt);
            }
        });
        Displayname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Displayname2ActionPerformed(evt);
            }
        });
        Displayname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Displayname2KeyPressed(evt);
            }
        });
        jPanel1.add(Displayname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 203, 130, 30));

        jPanel8.setBackground(new java.awt.Color(21, 25, 28));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(169, 224, 49));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/residents32#2.png"))); // NOI18N
        jLabel27.setText(" MY PROFILE");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Are you sure?", "Logout",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (selectedOption==JOptionPane.YES_OPTION){
            
        new LoginMain().setVisible(true);
        this.dispose();
        }
        /**this.dispose();**/
        //jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(ClickedColor);
        jPanel5.setBackground(DefaultColor);
        jPanel6.setBackground(DefaultColor);
        jPanel3.setBackground(DefaultColor);
        //jPanel7.setBackground(DefaultColor);
        jPanel8.setBackground(DefaultColor);
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(DefaultColor);
        jPanel5.setBackground(DefaultColor);
        jPanel6.setBackground(ClickedColor);
        jPanel3.setBackground(DefaultColor);
        //jPanel7.setBackground(DefaultColor);
        jPanel8.setBackground(DefaultColor);
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(DefaultColor);
        jPanel5.setBackground(ClickedColor);
        jPanel6.setBackground(DefaultColor);
        jPanel3.setBackground(DefaultColor);
        //jPanel7.setBackground(DefaultColor);
        jPanel8.setBackground(DefaultColor);
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(DefaultColor);
        jPanel5.setBackground(DefaultColor);
        jPanel6.setBackground(DefaultColor);
        jPanel3.setBackground(ClickedColor);
       // jPanel7.setBackground(DefaultColor);
                                       
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        MenuResidentRegister menu1 = new MenuResidentRegister();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(menu1).setVisible(true);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
//        Menu2 menu1 = new Menu2();
//        jDesktopPane1.removeAll();
//        jDesktopPane1.add(menu1).setVisible(true);
        MenuOfficialsRecords menu1 = new MenuOfficialsRecords();
        jRadioButton6.setVisible(true);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(menu1).setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
                String LoginAs = Displayname2.getText();
                String LoginAs1 = Lastname.getText();
                String LoginAs2 = Address.getText();
                
                MenuResidentRequestDocuments form = new MenuResidentRequestDocuments();
                form.jTextField_Firstname.setText(LoginAs);
                form.jTextField_Firstname1.setText(LoginAs1);
                form.jTextField_Firstname3.setText(LoginAs2);
//                form.setVisible(true);
//                form.pack();
                jDesktopPane1.removeAll();
                jDesktopPane1.add(form).setVisible(true);
        
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        String LoginAs = Displayname2.getText();
        //String LoginAs1 = Middlename.getText();
        //String LoginAs2 = Lastname.getText();
        MenuResidentReports menu1 = new MenuResidentReports();
        menu1.contact.setText(LoginAs);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(menu1).setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void Displayname2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Displayname2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Displayname2FocusGained

    private void Displayname2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Displayname2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Displayname2FocusLost

    private void Displayname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Displayname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Displayname2ActionPerformed

    private void Displayname2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Displayname2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Displayname2KeyPressed

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
        //jLabel_image.setVisible(true);
        String LoginAs = Displayname2.getText();
        String LoginAs1 = Middlename.getText();
        String LoginAs2 = Lastname.getText();
        String LoginAs3 = DOB.getText();
        String LoginAs4 = Age.getText();
        String LoginAs5 = Address.getText();
        String LoginAs6 = ID.getText();
        String LoginAs7 = Phonenumber.getText();
        String LoginAs8 = Gender.getText();
        Icon LoginAs9 = jLabel_image.getIcon();
        
//        byte[] img = getBytes();
//        ImageIcon image = new ImageIcon(img);
//        Image im = image.getImage();
//        Image myimg = im.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon newImage = new ImageIcon(myimg);
        //jLabel_image.setIcon(newImage);
        
        MenuResidentInformation menu1 = new MenuResidentInformation();
        menu1.jTextField_Firstname.setText(LoginAs);
        menu1.jTextField_Middlename.setText(LoginAs1);
        menu1.jTextField_Lastname.setText(LoginAs2);
        menu1.jTextField_DOB.setText(LoginAs3);
        menu1.jTextField_Age.setText(LoginAs4);
        menu1.jTextField_Address1.setText(LoginAs5);
        menu1.jTextField_ID.setText(LoginAs6);
        menu1.jTextField_Phonenumber.setText(LoginAs7);
        menu1.jTextField_Gender.setText(LoginAs8);
        menu1.jLabelProfileImage.setIcon(LoginAs9);
//        menu1.jLabelProfileImage.setIcon(newImage);
        //menu1.setVisible(true);
        //jDesktopPane1.removeAll();
        jDesktopPane1.add(menu1).setVisible(true);
    }//GEN-LAST:event_jPanel8MouseClicked
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        }
    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
        jPanel4.setBackground(DefaultColor);
        jPanel5.setBackground(DefaultColor);
        jPanel6.setBackground(DefaultColor);
        jPanel3.setBackground(DefaultColor);
        //jPanel7.setBackground(DefaultColor);
        jPanel8.setBackground(ClickedColor);
    }//GEN-LAST:event_jPanel8MousePressed

    private void GenderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GenderFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFocusGained

    private void GenderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GenderFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderFocusLost

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void GenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GenderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderKeyPressed

    private void FirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameFocusGained

    private void FirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameFocusLost

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void FirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameKeyPressed

    private void LastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameFocusGained

    private void LastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameFocusLost

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void LastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastnameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameKeyPressed

    private void MiddlenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddlenameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameFocusGained

    private void MiddlenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddlenameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameFocusLost

    private void MiddlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameActionPerformed

    private void MiddlenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MiddlenameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddlenameKeyPressed

    private void DOBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBFocusGained

    private void DOBFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBFocusLost

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void DOBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBKeyPressed

    private void AgeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFocusGained

    private void AgeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AgeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeFocusLost

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void AgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeKeyPressed

    private void AddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFocusGained

    private void AddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AddressFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFocusLost

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void AddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressKeyPressed

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFocusGained

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_IDFocusLost

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void IDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDKeyPressed

    private void PhonenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhonenumberFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumberFocusGained

    private void PhonenumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PhonenumberFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumberFocusLost

    private void PhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumberActionPerformed

    private void PhonenumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PhonenumberKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhonenumberKeyPressed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        BufferedImage img = null;
        if(jRadioButton6.isSelected()==true)
        {
            ImageIcon picture = new ImageIcon("src/Images2/ahong cover1.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:
        BufferedImage img = null;
        if(jRadioButton7.isSelected()==true)
        {
            ImageIcon picture = new ImageIcon("src/Images2/ahong cover2.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
        BufferedImage img = null;
        if(jRadioButton8.isSelected()==true)
        {
            ImageIcon picture = new ImageIcon("src/Images2/ahong1.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        BufferedImage img = null;
        if(jRadioButton9.isSelected()==true)
        {
            ImageIcon picture = new ImageIcon("src/Images2/ahong2.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
        BufferedImage img = null;
        if(jRadioButton10.isSelected()==true)
        {
            ImageIcon picture = new ImageIcon("src/Images2/ahong3.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Address;
    public javax.swing.JTextField Age;
    public javax.swing.JTextField DOB;
    public javax.swing.JTextField Displayname2;
    public javax.swing.JTextField Firstname;
    public javax.swing.JTextField Gender;
    public javax.swing.JTextField ID;
    public javax.swing.JTextField Lastname;
    public javax.swing.JTextField Middlename;
    public javax.swing.JTextField Phonenumber;
    private javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel_Image;
    public javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblTime2;
    // End of variables declaration//GEN-END:variables

    private byte[] getIcon() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private byte[] getBytes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

 
}
