/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayManagement;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.KeyEvent;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.mysql.jdbc.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.print.PrinterException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Jay Tanza
 */
public class MenuResidentRequestDocuments extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu1
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String imgPath = null;
    Object[] cols = null;
    String price = null;
    public MenuResidentRequestDocuments() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        populateJtable();
//        jLabel3.setVisible(false);
//        jLabel4.setVisible(false);
//        jLabel7.setVisible(false);
    }
    
    public void populateJtable()
    {
//       ResidentDocumentsQuery cq = new ResidentDocumentsQuery();
//       ArrayList<ResidentDocuments> ctList = cq.contactList();
//       String[] colNames = {"ID","First Name","Last Name","Address","Doc","Reason"};
//      Object[][]  rows = new Object[ctList.size()][6];
////       
//       for(int i=0; i<ctList.size(); i++)
//       {
//         rows[i][0] = ctList.get(i).getCid();
//         rows[i][1] = ctList.get(i).getFname();
//         rows[i][2] = ctList.get(i).getLname();
//         rows[i][3] = ctList.get(i).getAddress();
//         rows[i][4] = ctList.get(i).getDoc();
//         rows[i][5] = ctList.get(i).getReason();
//         
//         
////         ImageIcon pic = new ImageIcon(new ImageIcon(ctList.get(i).getPic()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
////         rows[i][5] = pic;
//       }
//       MyModel mmd = new MyModel(rows, colNames);
//       jTable2.setModel(mmd);
//       jTable2.setRowHeight(120);
//       jTable2.getColumnModel().getColumn(4).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelProfileImage = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_Documents1 = new javax.swing.JComboBox<>();
        jPanel_Print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Documents = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Firstname1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Firstname3 = new javax.swing.JTextField();
        jButton51 = new javax.swing.JButton();

        jLabelProfileImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

        jDesktopPane1.setLayer(jLabelProfileImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton49.setBackground(new java.awt.Color(169, 224, 49));
        jButton49.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton49.setForeground(new java.awt.Color(0, 0, 0));
        jButton49.setText("Select Image");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText("AGE:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(995, 692));

        jPanel42.setBackground(new java.awt.Color(0, 0, 0));
        jPanel42.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("REQUEST RECORDS/DOCUMENTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel42.add(jPanel1);
        jPanel1.setBounds(0, 0, 990, 50);

        jComboBox_Documents1.setBackground(new java.awt.Color(169, 224, 49));
        jComboBox_Documents1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jComboBox_Documents1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox_Documents1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Document", "Barangay Clearance ", "Barangay Certificate", "Barangay Permit", " " }));
        jComboBox_Documents1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Documents1ActionPerformed(evt);
            }
        });
        jPanel42.add(jComboBox_Documents1);
        jComboBox_Documents1.setBounds(160, 70, 340, 50);

        jPanel_Print.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("jLabel1");
        jPanel_Print.add(jLabel1);
        jLabel1.setBounds(240, 100, 40, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("jLabel1");
        jPanel_Print.add(jLabel9);
        jLabel9.setBounds(210, 90, 60, 20);

        jLabel_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jPanel_Print.add(jLabel_image);
        jLabel_image.setBounds(10, 10, 320, 470);

        jPanel42.add(jPanel_Print);
        jPanel_Print.setBounds(160, 130, 340, 490);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("Reason for Request :");
        jPanel42.add(jLabel5);
        jLabel5.setBounds(550, 140, 290, 40);

        jComboBox_Documents.setBackground(new java.awt.Color(0, 0, 0));
        jComboBox_Documents.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jComboBox_Documents.setForeground(new java.awt.Color(169, 224, 49));
        jComboBox_Documents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "School", "Application" }));
        jComboBox_Documents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_DocumentsActionPerformed(evt);
            }
        });
        jPanel42.add(jComboBox_Documents);
        jComboBox_Documents.setBounds(550, 180, 290, 50);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("Firstname :");
        jPanel42.add(jLabel3);
        jLabel3.setBounds(550, 260, 109, 24);

        jTextField_Firstname.setEditable(false);
        jTextField_Firstname.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_Firstname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextField_Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstnameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Firstname);
        jTextField_Firstname.setBounds(550, 290, 290, 40);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("Lastname :");
        jPanel42.add(jLabel6);
        jLabel6.setBounds(550, 340, 104, 24);

        jTextField_Firstname1.setEditable(false);
        jTextField_Firstname1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_Firstname1.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextField_Firstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Firstname1ActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Firstname1);
        jTextField_Firstname1.setBounds(550, 370, 290, 40);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("Address :");
        jPanel42.add(jLabel8);
        jLabel8.setBounds(550, 420, 89, 24);

        jTextField_Firstname3.setEditable(false);
        jTextField_Firstname3.setBackground(new java.awt.Color(0, 0, 0));
        jTextField_Firstname3.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jTextField_Firstname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Firstname3ActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Firstname3);
        jTextField_Firstname3.setBounds(550, 450, 290, 40);

        jButton51.setBackground(new java.awt.Color(0, 0, 0));
        jButton51.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton51.setForeground(new java.awt.Color(169, 224, 49));
        jButton51.setText("REQUEST DOCUMENT");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel42.add(jButton51);
        jButton51.setBounds(550, 520, 290, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
//        // TODO add your handling code here:
//        //String File;
//        /**JFileChooser fileChooser = new JFileChooser();
//        fileChooser.showOpenDialog(null);
//        File f = fileChooser.getSelectedFile();
//        String fileName = f.getAbsolutePath();
//        Path.setText(fileName);
//        Image getAsolutePath = null;
//        ImageIcon icon = new ImageIcon(fileName);
//        Image image = icon.getImage().getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_DEFAULT);
//        jLabelProfileImage.setIcon(icon);
//        jLabelProfileImage.setIcon(ResizeImage(f));**/
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jpg","*.png","*.gif","*.bmp");
//        fileChooser.addChoosableFileFilter(filter);
//        int result=fileChooser.showSaveDialog(null);
//        if(result==JFileChooser.APPROVE_OPTION){
//            File selectedFile = fileChooser.getSelectedFile();
//            String path = selectedFile.getAbsolutePath();
//            jLabelProfileImage.setIcon(ResizeImage(path));
//            String s = path;
//            //cmdRegisterWithImage.setVisible(true);
//            //cmdRegister.setVisible(false);
//        }else if(result==JFileChooser.CANCEL_OPTION){
//            jLabelProfileImage.setIcon(null);
//            //cmdRegister.setVisible(true);
//            //cmdRegisterWithImage.setVisible(false);
//            JOptionPane.showMessageDialog(null, "Select an Image","Barangay System",JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jComboBox_Documents1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Documents1ActionPerformed
        // TODO add your handling code here:
        jLabel9.setVisible(true);
        jLabel1.setVisible(true);
        BufferedImage img = null;
        if(jComboBox_Documents1.getSelectedItem()=="Select Document")
        {
            jLabel_image.setIcon(null);
        }
        else if(jComboBox_Documents1.getSelectedItem()=="Barangay Clearance")
        {
            ImageIcon picture = new ImageIcon("src/BarangayDocumentsPic/BarangayMactanClearance1.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
            jLabel_image.setIcon(new ImageIcon(image1));

        }
        else if(jComboBox_Documents1.getSelectedItem()=="Barangay Certificate")
        {
            ImageIcon picture = new ImageIcon("src/BarangayDocumentsPic/BarangayMactanCertificate.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
            jLabel_image.setIcon(new ImageIcon(image1));
        }
        else if(jComboBox_Documents1.getSelectedItem()=="Barangay Permit")
        {
            ImageIcon picture = new ImageIcon("src/BarangayDocumentsPic/BarangayMactanPermit.jpg");
            Image image1 = picture.getImage().getScaledInstance(jLabel_image.getWidth(), jLabel_image.getHeight(), Image.SCALE_SMOOTH);
            jLabel_image.setIcon(new ImageIcon(image1));
        }
    }//GEN-LAST:event_jComboBox_Documents1ActionPerformed

    private void jComboBox_DocumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DocumentsActionPerformed
        // TODO add your handling code here:
        //BufferedImage picture = null;

    }//GEN-LAST:event_jComboBox_DocumentsActionPerformed

    private void jTextField_FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstnameActionPerformed

    private void jTextField_Firstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Firstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Firstname1ActionPerformed

    private void jTextField_Firstname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Firstname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Firstname3ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        //INSERT INTO `requestdoc`(`Firstname`, `Lastname`, `Address`, `Doc`, `Reason`) VALUES (?,?,?,?,?)
        String registerUserQuery = "INSERT INTO `requestdoc`(`Firstname`, `Lastname`, `Address`, `Doc`, `Reason`) VALUES (?,?,?,?,?)";
        try{
            //InputStream is = new FileInputStream(new File(s));
            pst = (PreparedStatement) MyConnection.getConnection().prepareStatement(registerUserQuery);
            pst.setString(1,jTextField_Firstname.getText());
            pst.setString(2,jTextField_Firstname1.getText());
            pst.setString(3,jTextField_Firstname3.getText());
            pst.setString(4,jComboBox_Documents1.getSelectedItem().toString());
            pst.setString(5,jComboBox_Documents.getSelectedItem().toString());
            pst.executeUpdate();
        }
          catch (SQLException ex) {
            Logger.getLogger(ReqDoc.class.getName()).log(Level.SEVERE, null, ex);
        }
         JOptionPane.showMessageDialog(null, "Request Successfully Registered","Barangay System",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton51ActionPerformed
         
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        }
    //    public ImageIcon ResizeImage(String imgPath){
//        ImageIcon MyImage = new ImageIcon(imgPath);
//        Image img = MyImage.getImage();
//        Image newImage = img.getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(newImage);
//        return image;
//        }    /**public void showTable() 
//    {
//       String registerUserQuery = "SELECT * FROM residentaccountinfo";
//       try {
//        ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
//        rs = ps.executeQuery();
//       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//       
//       }catch (SQLException ex) {
//                   JOptionPane.showMessageDialog(null, ex);
//                }
//    }**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton51;
    private javax.swing.JComboBox<String> jComboBox_Documents;
    private javax.swing.JComboBox<String> jComboBox_Documents1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfileImage;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel_Print;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField_Firstname;
    public javax.swing.JTextField jTextField_Firstname1;
    public javax.swing.JTextField jTextField_Firstname3;
    // End of variables declaration//GEN-END:variables
//    private void printRecord(JPanel jPanel_Print)
//    {   
//      PrinterJob printerJob = PrinterJob.getPrinterJob();
//      
//      printerJob.setJobName("Print Document");
//      printerJob.setPrintable(new Printable)
//      {
//        //@Override
//        public int print(Graphics graphics, PageFormat pageformat, int pageIndex) throws PrinterException
//        {
//      if (pageIndex > 0){
//      return Printable.NO_SUCH_PAGE;
//      }
//      Graphics2D g2 = (Graphics2D) graphics;
//      g2.translate(pageformat.getImageableX(), pageformat.getImageableY());
//      jPanel_Print.paint(g2);
//      //JOptionPane.showMessageDialog(null, "Reciept Printed...","Barangay System",JOptionPane.INFORMATION_MESSAGE);
//      return Printable.PAGE_EXISTS;
//       }
//     });
//         boolean returningResult = printerJob.printDialog();
//        
//        if(returningResult)
//      {
//             try
//             {
//               printerJob.print();
//             }catch(PrinterException printerException)
//          {
//             JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMesage());
//          }
//      }
//    }
//}
//    private Icon ResizeImage(File f) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    private BufferedImage resize(BufferedImage bi, int width, int height) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    

   
}
