/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayManagement;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.mysql.jdbc.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Jay Tanza
 */
public class MenuResidentRecords extends javax.swing.JInternalFrame {

    /**
     * Creates new form Menu1
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String imgPath = null;
    Object[] cols = null;
    public MenuResidentRecords() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        populateJtable();
    }
    
    public void populateJtable()
    {
       ResidentRecordsQuery cq = new ResidentRecordsQuery();
       ArrayList<ResidentRecords> ctList = cq.contactList();
       String[] colNames = {"ID","First Name","Middle Name","Last Name","Address","Picture"};
       Object[][]  rows = new Object[ctList.size()][6];
       
       for(int i=0; i<ctList.size(); i++)
       {
         rows[i][0] = ctList.get(i).getCid();
         rows[i][1] = ctList.get(i).getFname();
         rows[i][2] = ctList.get(i).getMname();
         rows[i][3] = ctList.get(i).getLname();
         rows[i][4] = ctList.get(i).getAddress();
         if(ctList.get(i).getPic() !=null)
         {
             ImageIcon pic = new ImageIcon(new ImageIcon(ctList.get(i).getPic()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
             rows[i][5] = pic;
         }
         else
         {
             rows[i][5] = null;
         }
         
         
//         ImageIcon pic = new ImageIcon(new ImageIcon(ctList.get(i).getPic()).getImage().getScaledInstance(150, 120, Image.SCALE_SMOOTH));
//         rows[i][5] = pic;
       }
       MyModel mmd = new MyModel(rows, colNames);
       jTable2.setModel(mmd);
       jTable2.setRowHeight(120);
       jTable2.getColumnModel().getColumn(5).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelProfileImage = new javax.swing.JLabel();
        jButton49 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel42 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Firstname = new javax.swing.JTextField();
        jTextField_Address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Middlename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabelProfileImage1 = new javax.swing.JLabel();
        rqstdoc = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton_Add = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField_Age = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Phonenumber = new javax.swing.JTextField();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_Gender = new javax.swing.JTextField();
        jTextField_DOB = new javax.swing.JTextField();

        jLabelProfileImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

        jDesktopPane1.setLayer(jLabelProfileImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton49.setBackground(new java.awt.Color(169, 224, 49));
        jButton49.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton49.setForeground(new java.awt.Color(0, 0, 0));
        jButton49.setText("Select Image");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(169, 224, 49));
        jLabel12.setText("AGE:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(995, 692));

        jPanel42.setBackground(new java.awt.Color(0, 0, 0));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("FIRST NAME :");
        jPanel42.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("LAST NAME :");
        jPanel42.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("PROFILE PICTURE:");
        jPanel42.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jTextField_Firstname.setEditable(false);
        jTextField_Firstname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Firstname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstnameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));

        jTextField_Address.setEditable(false);
        jTextField_Address.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Address.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Address.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AddressActionPerformed(evt);
            }
        });
        jTextField_Address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AddressKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 270, 30));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("ADDRESS :");
        jPanel42.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 90, -1));

        jTextField_Lastname.setEditable(false);
        jTextField_Lastname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Lastname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Lastname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LastnameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 260, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("MIDDLE NAME :");
        jPanel42.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextField_Middlename.setEditable(false);
        jTextField_Middlename.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Middlename.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Middlename.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Middlename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MiddlenameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("DATE OF BIRTH:");
        jPanel42.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(169, 224, 49));
        jLabel9.setText("GENDER :");
        jPanel42.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 80, -1));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("RESIDENT RECORDS");

        jTextField_Search.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Search.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Search.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SearchFocusLost(evt);
            }
        });
        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("SEARCH:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel2)
                .addGap(118, 118, 118)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel42.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 50));

        jLabelProfileImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

        jDesktopPane2.setLayer(jLabelProfileImage1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProfileImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProfileImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel42.add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 220, 170));

        rqstdoc.setBackground(new java.awt.Color(169, 224, 49));
        rqstdoc.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rqstdoc.setForeground(new java.awt.Color(0, 0, 0));
        rqstdoc.setText("REQUEST DOCUMENT");
        rqstdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rqstdocActionPerformed(evt);
            }
        });
        jPanel42.add(rqstdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 220, 30));

        jButton54.setBackground(new java.awt.Color(0, 0, 0));
        jButton54.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton54.setForeground(new java.awt.Color(169, 224, 49));
        jButton54.setText("Delete");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel42.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 260, 140, 40));

        jButton51.setBackground(new java.awt.Color(0, 0, 0));
        jButton51.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton51.setForeground(new java.awt.Color(169, 224, 49));
        jButton51.setText("Update");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel42.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, 140, 40));

        jButton_Add.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Add.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(169, 224, 49));
        jButton_Add.setText("Add");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        jPanel42.add(jButton_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 140, 40));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(169, 224, 49));
        jLabel10.setText("PHONE NUMBER:");
        jPanel42.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 130, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(169, 224, 49));
        jLabel13.setText("ID#");
        jPanel42.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 40, 10));

        jTable2.setBackground(new java.awt.Color(31, 36, 42));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel42.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 950, 320));

        jTextField_Age.setEditable(false);
        jTextField_Age.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Age.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 270, 30));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(169, 224, 49));
        jLabel15.setText("AGE:");
        jPanel42.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 50, 10));

        jTextField_Phonenumber.setEditable(false);
        jTextField_Phonenumber.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Phonenumber.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Phonenumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhonenumberActionPerformed(evt);
            }
        });
        jTextField_Phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhonenumberKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_Phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 270, 30));

        jTextField_ID.setEditable(false);
        jTextField_ID.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_ID.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_ID.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 140, 30));

        jTextField_Gender.setEditable(false);
        jTextField_Gender.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Gender.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Gender.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GenderActionPerformed(evt);
            }
        });
        jTextField_Gender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_GenderKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 270, 30));

        jTextField_DOB.setEditable(false);
        jTextField_DOB.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_DOB.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_DOB.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_DOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_DOBActionPerformed(evt);
            }
        });
        jTextField_DOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DOBKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_MiddlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MiddlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MiddlenameActionPerformed

    private void jTextField_FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstnameActionPerformed

    private void jTextField_LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LastnameActionPerformed

    private void jTextField_AddressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AddressKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AddressKeyTyped

    private void jTextField_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AddressActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
//        // TODO add your handling code here:
//        //String File;
//        /**JFileChooser fileChooser = new JFileChooser();
//        fileChooser.showOpenDialog(null);
//        File f = fileChooser.getSelectedFile();
//        String fileName = f.getAbsolutePath();
//        Path.setText(fileName);
//        Image getAsolutePath = null;
//        ImageIcon icon = new ImageIcon(fileName);
//        Image image = icon.getImage().getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_DEFAULT);
//        jLabelProfileImage.setIcon(icon);
//        jLabelProfileImage.setIcon(ResizeImage(f));**/
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jpg","*.png","*.gif","*.bmp");
//        fileChooser.addChoosableFileFilter(filter);
//        int result=fileChooser.showSaveDialog(null);
//        if(result==JFileChooser.APPROVE_OPTION){
//            File selectedFile = fileChooser.getSelectedFile();
//            String path = selectedFile.getAbsolutePath();
//            jLabelProfileImage.setIcon(ResizeImage(path));
//            String s = path;
//            //cmdRegisterWithImage.setVisible(true);
//            //cmdRegister.setVisible(false);
//        }else if(result==JFileChooser.CANCEL_OPTION){
//            jLabelProfileImage.setIcon(null);
//            //cmdRegister.setVisible(true);
//            //cmdRegisterWithImage.setVisible(false);
//            JOptionPane.showMessageDialog(null, "Select an Image","Barangay System",JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_jButton49ActionPerformed
    
    private void rqstdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rqstdocActionPerformed

//       TableModel model1 = jTable2.getModel();
//       int indexs[] = jTable2.getSelectedRows();
//       
//       Object[] row = new Object[6];
//       
//       MenuResidentDocuments menu = new MenuResidentDocuments();
//       DefaultTableModel model2 = (DefaultTableModel)menu.jTable3.getModel();
//       
//       for(int i=0; i<indexs.length; i++)
//       {
//         row[0] = model1.getValueAt(indexs[i],0);    
//         row[1] = model1.getValueAt(indexs[i],1); 
//         row[2] = model1.getValueAt(indexs[i],2);  
//         row[3] = model1.getValueAt(indexs[i],3);  
//         row[4] = model1.getValueAt(indexs[i],4); 
//         row[5] = model1.getValueAt(indexs[i],5); 
//         model2.addRow(row);
//       }
//       menu.setVisible(true);
////       MyModel mmd = new MyModel(row, colNames);
////       menu.jTable3.setModel(mmd);
//       //menu.jTable3.setRowHeight(120);
//       //menu.jTable3.getColumnModel().getColumn(5).setPreferredWidth(150);
    }//GEN-LAST:event_rqstdocActionPerformed
     
    public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabelProfileImage1.getWidth(), jLabelProfileImage1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        }
    
    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
        String registerUserQuery = "UPDATE `residentaccountinfo` SET`Lastname`=?,`Age`=?,`Address`=?,`Phonenumber`=?,`Birthdate`=? WHERE Firstname=?";
        String fname = jTextField_Firstname.getText();
        String lname = jTextField_Lastname.getText();
        String Age = jTextField_Search.getText();
        String Address= jTextField_Address.getText();
        String Phonenumber= jTextField_Phonenumber.getText();
        //var Birthdate = ((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText();
        String Birthdate = jTextField_DOB.getText();
        try {
            pst = MyConnection.getConnection().prepareStatement(registerUserQuery);
            pst.setString(6, fname);
            pst.setString(1, lname);
            pst.setString(2, Age);
            pst.setString(3, Address);
            pst.setString(4, Phonenumber);
            pst.setString(5, Birthdate);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Updated Successfully!");

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        //showTable();
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // TODO add your handling code here:
        if(jTextField_Firstname.getText().equals("") || jTextField_Middlename.getText().equals("") || jTextField_Lastname.getText().equals("") || jTextField_DOB.getText().equals("")
           || jTextField_Address.getText().equals("") ||  jLabelProfileImage1.getIcon().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Specified the Required Fields  (  *  )","Barangay System",JOptionPane.ERROR_MESSAGE);
        }
        
        else
        {
            String registerUserQuery = "INSERT INTO `residentaccountinfo`(`Firstname`, `Middlename`, `Lastname`, `Birthdate`, `Age`, `Phonenumber`, `Address`, `Gender`, `profilepic`) VALUES (?,?,?,?,?,?,?,?,?)";
            int selectedOption = JOptionPane.showConfirmDialog(null, "Are you sure?", "Barangay System",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (selectedOption==JOptionPane.YES_OPTION)
            {
                try{
                    InputStream img = new FileInputStream(new File(imgPath));
                    pst = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    //InputStream is = new FileInputStream(new File(s));
                    pst.setString(1,jTextField_Firstname.getText());
                    pst.setString(2,jTextField_Middlename.getText());
                    pst.setString(3,jTextField_Lastname.getText());
                    //pst.setString(4,((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText());
                    pst.setString(3,jTextField_DOB.getText());
                    pst.setString(5,jTextField_Age.getText());
                    pst.setString(6,jTextField_Phonenumber.getText());
                    pst.setString(7,jTextField_Address.getText());
                    pst.setString(8,jTextField_Gender.getText());
                    pst.setBlob(9,img);
                    pst.executeUpdate();

                }   catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                //con.close();
                JOptionPane.showMessageDialog(null, "User Successfully Registered","Barangay System",JOptionPane.INFORMATION_MESSAGE);
                jTextField_Firstname.getText().equals(null);
                jTextField_Middlename.getText().equals(null);
                jTextField_Lastname.getText().equals(null);
                //jDateChooser_DOB.getDate().equals(null);
                jTextField_DOB.getText().equals(null);
                jTextField_Search.getText().equals(null);
                jTextField_Address.getText().equals(null);
                jLabelProfileImage1.getIcon().equals(null);
            }
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        jTextField_ID.setText(model.getValueAt(i,0).toString());
        jTextField_Firstname .setText(model.getValueAt(i,1).toString());
        jTextField_Middlename .setText(model.getValueAt(i,2).toString());
        jTextField_Lastname.setText(model.getValueAt(i,3).toString());
        jTextField_Address.setText(model.getValueAt(i,4).toString());
        
        if(jTable2.getValueAt(i,5)!=null)
        {
        ImageIcon image=(ImageIcon)jTable2.getValueAt(i,5);
        Image image2=image.getImage().getScaledInstance(jLabelProfileImage1.getWidth(),jLabelProfileImage1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image3=new ImageIcon(image2);
        jLabelProfileImage1.setIcon(image3);
        }
        else
        {
            System.out.println("No image");
        }
          try
         {
             String sql2 = "SELECT `Firstname`, `ResidentID`, `Middlename`, `Lastname`, `Birthdate`, `Age`, `Phonenumber`, `Address`, `Gender`, `profilepic` FROM `residentaccountinfo` where Firstname=?";
             pst = MyConnection.getConnection().prepareStatement(sql2);
             pst.setString(1,jTextField_Search.getText());
             ResultSet rs = pst.executeQuery();
             if(rs.next())
             {
               String setid = rs.getString("ResidentID");
               jTextField_ID.setText(setid);
               
               String setname = rs.getString("Firstname");
               jTextField_Firstname.setText(setname);
               
               String setname2 = rs.getString("Middlename");
               jTextField_Lastname.setText(setname2);
               
               String setname3 = rs.getString("Lastname");
               jTextField_Middlename.setText(setname3);
               
               String address = rs.getString("Address");
               jTextField_Address.setText(address);
               
//               String Birthdate = rs.getString("Birthdate"); // What ever column
//               java.util.Date date = new SimpleDateFormat("").parse(Birthdate);
//               jDateChooser_DOB.setDate(date);
              String DOB = rs.getString("Birthdate");
               jTextField_DOB.setText(DOB); 
              
               String Age = rs.getString("Age");
               jTextField_Age.setText(Age);
               
               String Phonenumber = rs.getString("Phonenumber");
               jTextField_Phonenumber.setText(Phonenumber);
               
               String Gender = rs.getString("Gender");
               jTextField_Gender.setText(Gender);
               

               
               byte[] img = rs.getBytes("profilepic");
               ImageIcon image = new ImageIcon(img);
               Image im = image.getImage();
               Image myimg = im.getScaledInstance(jLabelProfileImage1.getWidth(), jLabelProfileImage1.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon newImage = new ImageIcon(myimg);
               jLabelProfileImage1.setIcon(newImage);
             }
         }
         catch (Exception ex) 
         {
             JOptionPane.showMessageDialog(null, ex);
         }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField_PhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhonenumberActionPerformed

    private void jTextField_PhonenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhonenumberKeyTyped

    private void jTextField_SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SearchFocusGained
        // TODO add your handling code here:
        if(jTextField_Search.getText().trim().equals("") ||
            jTextField_Search.getText().trim().toLowerCase().equals("Search Residents Here"))
        {
            jTextField_Search.setText("");
            jTextField_Search.setForeground(Color.WHITE);
        }
    }//GEN-LAST:event_jTextField_SearchFocusGained

    private void jTextField_SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SearchFocusLost
        // TODO add your handling code here:
        if(jTextField_Search.getText().trim().toLowerCase().equals("Search Residents Here"))
        {
            jTextField_Search.setText("Search Residents Here");
            // change the text field color to black
            jTextField_Search.setForeground(Color.white);
        }
    }//GEN-LAST:event_jTextField_SearchFocusLost

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
//        // TODO add your handling code here:
         try
         {
             String sql2 = "SELECT `Firstname`, `ResidentID`, `Middlename`, `Lastname`, `Birthdate`, `Age`, `Phonenumber`, `Address`, `Gender`, `profilepic` FROM `residentaccountinfo` where Firstname=?";
             pst = MyConnection.getConnection().prepareStatement(sql2);
             pst.setString(1,jTextField_Search.getText());
             ResultSet rs = pst.executeQuery();
             if(rs.next())
             {
               String setid = rs.getString("ResidentID");
               jTextField_ID.setText(setid);
               
               String setname = rs.getString("Firstname");
               jTextField_Firstname.setText(setname);
               
               String setname2 = rs.getString("Middlename");
               jTextField_Lastname.setText(setname2);
               
               String setname3 = rs.getString("Lastname");
               jTextField_Middlename.setText(setname3);
               
               String address = rs.getString("Address");
               jTextField_Address.setText(address);
               
//               String Birthdate = rs.getString("Birthdate"); // What ever column
//               java.util.Date date = new SimpleDateFormat("").parse(Birthdate);
//               jDateChooser_DOB.setDate(date);
               String DOB = rs.getString("Birthdate");
               jTextField_DOB.setText(DOB);
               

               String Age = rs.getString("Age");
               jTextField_Age.setText(Age);
               
               String Phonenumber = rs.getString("Phonenumber");
               jTextField_Phonenumber.setText(Phonenumber);
               
               String Gender = rs.getString("Gender");
               jTextField_Gender.setText(Gender);
               
               
               byte[] img = rs.getBytes("profilepic");
               ImageIcon image = new ImageIcon(img);
               Image im = image.getImage();
               Image myimg = im.getScaledInstance(jLabelProfileImage1.getWidth(), jLabelProfileImage1.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon newImage = new ImageIcon(myimg);
               jLabelProfileImage1.setIcon(newImage);
             }
         }
         catch (Exception ex) 
         {
             JOptionPane.showMessageDialog(null, ex);
         }
         
       try
         {
             String sql2 = "SELECT `Firstname`, `ResidentID`, `Middlename`, `Lastname`, `Birthdate`, `Age`, `Phonenumber`, `Address`, `Gender`, `profilepic` FROM `residentaccountinfo` where Lastname=?";
             pst = MyConnection.getConnection().prepareStatement(sql2);
             pst.setString(1,jTextField_Search.getText());
             ResultSet rs = pst.executeQuery();
             if(rs.next())
             {
               String setid = rs.getString("ResidentID");
               jTextField_ID.setText(setid);
               
               String setname = rs.getString("Firstname");
               jTextField_Firstname.setText(setname);
               
               String setname2 = rs.getString("Middlename");
               jTextField_Lastname.setText(setname2);
               
               String setname3 = rs.getString("Lastname");
               jTextField_Middlename.setText(setname3);
               
               String address = rs.getString("Address");
               jTextField_Address.setText(address);
               
//               String Birthdate = rs.getString("Birthdate"); // What ever column
//               java.util.Date date = new SimpleDateFormat("").parse(Birthdate);
//               jDateChooser_DOB.setDate(date);
               
               String Age = rs.getString("Age");
               jTextField_Age.setText(Age);
               
               String Phonenumber = rs.getString("Phonenumber");
               jTextField_Phonenumber.setText(Phonenumber);
               
               String Gender = rs.getString("Gender");
               jTextField_Gender.setText(Gender);
               
               
               byte[] img = rs.getBytes("profilepic");
               ImageIcon image = new ImageIcon(img);
               Image im = image.getImage();
               Image myimg = im.getScaledInstance(jLabelProfileImage1.getWidth(), jLabelProfileImage1.getHeight(), Image.SCALE_SMOOTH);
               ImageIcon newImage = new ImageIcon(myimg);
               jLabelProfileImage1.setIcon(newImage);
             }
         }
         catch (Exception ex) 
         {
             JOptionPane.showMessageDialog(null, ex);
         }
       
       
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void jTextField_GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenderActionPerformed

    private void jTextField_GenderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_GenderKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GenderKeyTyped

    private void jTextField_DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DOBActionPerformed

    private void jTextField_DOBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DOBKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DOBKeyTyped
//    public ImageIcon ResizeImage(String imgPath){
//        ImageIcon MyImage = new ImageIcon(imgPath);
//        Image img = MyImage.getImage();
//        Image newImage = img.getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image = new ImageIcon(newImage);
//        return image;
//        }    /**public void showTable() 
//    {
//       String registerUserQuery = "SELECT * FROM residentaccountinfo";
//       try {
//        ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
//        rs = ps.executeQuery();
//       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
//       
//       }catch (SQLException ex) {
//                   JOptionPane.showMessageDialog(null, ex);
//                }
//    }**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfileImage;
    private javax.swing.JLabel jLabelProfileImage1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_DOB;
    private javax.swing.JTextField jTextField_Firstname;
    private javax.swing.JTextField jTextField_Gender;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Lastname;
    private javax.swing.JTextField jTextField_Middlename;
    private javax.swing.JTextField jTextField_Phonenumber;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JButton rqstdoc;
    // End of variables declaration//GEN-END:variables

//    private Icon ResizeImage(File f) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//
//    private BufferedImage resize(BufferedImage bi, int width, int height) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    

   
}
