/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BarangayManagement;

import com.sun.jdi.connect.spi.Connection;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.mysql.jdbc.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Jay Tanza
 */
public class PrintingForm extends javax.swing.JFrame {

    /**
     * Creates new form PrintingForm
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    Object[] cols = null;
    public PrintingForm() {
        initComponents();
        showTable();
    }
    
    public void updateDB()
    {
       String registerUserQuery = "INSERT INTO `residentaccountinfo`(`Firstname`, `Lastname`,`Age`, `Address`, `Phonenumber`, `Birthdate`) VALUES (?,?,?,?,?,?)";

                String fname = jTextField_Firstname.getText();
                String lname = jTextField_Firstname.getText();
                String Age = jTextField_Age.getText();
                String Address= jComboBox_Address.getSelectedItem().toString();
                String Phonenumber= jTextField_Phonenumber.getText();
                var Birthdate = ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
       
                try {
                    ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, Age);
                    ps.setString(4, Address);
                    ps.setString(5, Phonenumber);
                    ps.setString(6, Birthdate);

                    if(ps.executeUpdate() != 0)
                    {
                        JOptionPane.showMessageDialog(null, "Your Profile Information Has Been Created");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }

                }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
                showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Firstname = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Phonenumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBox_Address = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Lastname = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("LAST NAME :");

        jButton4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton4.setText("Add New");

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(169, 224, 49));
        jButton10.setText("Delete");

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton14.setForeground(new java.awt.Color(169, 224, 49));
        jButton14.setText("Print");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));

        jTable1.setForeground(new java.awt.Color(102, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Firstname", "Lastname", "Address", "Phonenumber", "Birthdate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jTable1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTable1HierarchyChanged(evt);
            }
        });
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jTable1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 0, 470, 591));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("FIRST NAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("RESIDENT  RECORDS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 330, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("LAST NAME :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("AGE:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("PHONE NUMBER:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jDateChooser.setBackground(new java.awt.Color(31, 36, 42));
        jDateChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jDateChooser.setForeground(new java.awt.Color(31, 36, 42));
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 40));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("BIRTH DATE:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jTextField_Firstname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Firstname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 330, 40));

        jTextField_Age.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Age.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 40));

        jTextField_Phonenumber.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Phonenumber.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Phonenumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhonenumberActionPerformed(evt);
            }
        });
        jTextField_Phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhonenumberKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_Phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 330, 40));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(169, 224, 49));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 110, 40));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(169, 224, 49));
        jButton8.setText("Print");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 110, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(169, 224, 49));
        jButton9.setText("Insert");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 110, 40));

        jButton13.setBackground(new java.awt.Color(0, 0, 0));
        jButton13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(169, 224, 49));
        jButton13.setText("Reset");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 110, 40));

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(169, 224, 49));
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 110, 40));

        jButton15.setBackground(new java.awt.Color(0, 0, 0));
        jButton15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(169, 224, 49));
        jButton15.setText("Update");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 110, 40));

        jComboBox_Address.setBackground(new java.awt.Color(31, 36, 42));
        jComboBox_Address.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox_Address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MACTAN", "IBO", "SOONG I", "SOONG II", "ENGANO", "ANGASIL", "KAKONSOR", "IBAPO", "KASANTA", " " }));
        jComboBox_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jPanel1.add(jComboBox_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 160, 40));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("ADDRESS :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jTextField_Lastname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Lastname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Lastname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LastnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 330, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstnameActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_PhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhonenumberActionPerformed
private JFrame frame;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","MySQL Connector",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
           System.exit(0);
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jTextField_Firstname.setText("");
        jTextField_Age.setText("");
        jTextField_Phonenumber.setText(""); 
        jDateChooser.setDate(null);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTextField_PhonenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
           evt.consume();
        }
           
    }//GEN-LAST:event_jTextField_PhonenumberKeyTyped

    private void jTextField_LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LastnameActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String registerUserQuery = "INSERT INTO `residentaccountinfo`(`Firstname`, `Lastname`,`Age`, `Address`, `Phonenumber`, `Birthdate`) VALUES (?,?,?,?,?,?)";

                String fname = jTextField_Firstname.getText();
                String lname = jTextField_Lastname.getText();
                String Age = jTextField_Age.getText();
                String Address= jComboBox_Address.getSelectedItem().toString();
                String Phonenumber= jTextField_Phonenumber.getText();
                var Birthdate = ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
       
                try {
                    ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, Age);
                    ps.setString(4, Address);
                    ps.setString(5, Phonenumber);
                    ps.setString(6, Birthdate);

                    if(ps.executeUpdate() != 0)
                    {
                        JOptionPane.showMessageDialog(null, "Your Profile Information Has Been Created");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }

                }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
                showTable();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String registerUserQuery = "DELETE FROM `residentaccountinfo` WHERE Firstname =?";
        String fname = jTextField_Firstname.getText();
        var Birthdate = ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
            try {
                    ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,fname);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Delete Successfully!");
                    

                }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
            showTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        String registerUserQuery = "UPDATE `residentaccountinfo` SET`Lastname`=?,`Age`=?,`Address`=?,`Phonenumber`=?,`Birthdate`=? WHERE Firstname=?";
        String fname = jTextField_Firstname.getText();
        String lname = jTextField_Lastname.getText();
        String Age = jTextField_Age.getText();
        String Address= jComboBox_Address.getSelectedItem().toString();
        String Phonenumber= jTextField_Phonenumber.getText();
        var Birthdate = ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText();
            try {
                    ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(6, fname);
                    ps.setString(1, lname);
                    ps.setString(2, Age);
                    ps.setString(3, Address);
                    ps.setString(4, Phonenumber);
                    ps.setString(5, Birthdate);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Updated Successfully!");
                    

                }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
            showTable();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1FocusGained

    private void jTable1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable1HierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1HierarchyChanged

    private void jTable1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1CaretPositionChanged

    /**
     * @param args the command line arguments
     */
    
    public void showTable() 
    {
       String registerUserQuery = "SELECT `ResidentID`, `Firstname`, `Middlename`, `Lastname`,`Address`,`profilepic` FROM residentaccountinfo";
       try {
       ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
       rs = ps.executeQuery();
       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       //String[] colNames = {"ID","First Name","Middle Name","Last Name","Address","Picture"};
       cols = new String[]{"Resident ID","First Name","Middle Name","Last Name","Picture"};
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setColumnIdentifiers(cols);
//       jTable1.setRowHeight(100);
//       jTable1.getColumnModel().getColumn(7).setPreferredWidth(250);
//        pst=conn.prepareStatement(sql); 
//          //  pst.setString(1,jTextField1.getText()); 
//            rs=pst.executeQuery();
//            tblResidents.setModel(DbUtils.resultSetToTableModel(rs)); 
//            cols = new String[]{"Resident ID","First Name","Middle Name","Last Name"};
//            DefaultTableModel model = (DefaultTableModel) tblResidents.getModel();
//            model.setColumnIdentifiers(cols);
       }catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, ex);
                }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox_Address;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_Firstname;
    private javax.swing.JTextField jTextField_Lastname;
    private javax.swing.JTextField jTextField_Phonenumber;
    // End of variables declaration//GEN-END:variables
}
