package BarangayManagement;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.KeyEvent;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.mysql.jdbc.Statement;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Jay Tanza
 */
public class ResidentProfile extends javax.swing.JFrame {

    /**
     * Creates new form ResidentProfile
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String imgPath = null;
    public ResidentProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel42 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jLabel251 = new javax.swing.JLabel();
        jTextField_FathersName = new javax.swing.JTextField();
        jLabel252 = new javax.swing.JLabel();
        jTextField_MothersName = new javax.swing.JTextField();
        jLabel253 = new javax.swing.JLabel();
        jTextField_YourOccupation = new javax.swing.JTextField();
        jLabel254 = new javax.swing.JLabel();
        jTextField_Religion = new javax.swing.JTextField();
        jLabel257 = new javax.swing.JLabel();
        jTextField_NumberofSiblings = new javax.swing.JTextField();
        jLabel258 = new javax.swing.JLabel();
        jComboBox_Birthrank = new javax.swing.JComboBox<>();
        jLabel259 = new javax.swing.JLabel();
        jButton_SelectImage = new javax.swing.JButton();
        jPanel43 = new javax.swing.JPanel();
        Updatebtn = new javax.swing.JButton();
        Clearbtn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelProfileImage = new javax.swing.JLabel();
        Jlabelimg_path = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Firstname = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Phonenumber = new javax.swing.JTextField();
        jComboBox_Address = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Middlename = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_DOB = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Gender = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel42.setBackground(new java.awt.Color(0, 0, 0));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBackground(new java.awt.Color(21, 25, 28));

        jLabel251.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel251.setForeground(new java.awt.Color(169, 224, 49));
        jLabel251.setText("FATHERS NAME :");

        jTextField_FathersName.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_FathersName.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_FathersName.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_FathersName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_FathersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FathersNamejTextField_Firstname2ActionPerformed(evt);
            }
        });

        jLabel252.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel252.setForeground(new java.awt.Color(169, 224, 49));
        jLabel252.setText("MOTHERS NAME :");

        jTextField_MothersName.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_MothersName.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_MothersName.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_MothersName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_MothersName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MothersNamejTextField_Firstname3ActionPerformed(evt);
            }
        });

        jLabel253.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel253.setForeground(new java.awt.Color(169, 224, 49));
        jLabel253.setText("YOUR OCCUPATION  :");

        jTextField_YourOccupation.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_YourOccupation.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_YourOccupation.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_YourOccupation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_YourOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_YourOccupationjTextField_Firstname4ActionPerformed(evt);
            }
        });

        jLabel254.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel254.setForeground(new java.awt.Color(169, 224, 49));
        jLabel254.setText("RELIGION  :");

        jTextField_Religion.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Religion.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Religion.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ReligionjTextField_Firstname5ActionPerformed(evt);
            }
        });

        jLabel257.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel257.setForeground(new java.awt.Color(169, 224, 49));
        jLabel257.setText("NUMBER OF SIBLINGS :");

        jTextField_NumberofSiblings.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_NumberofSiblings.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_NumberofSiblings.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_NumberofSiblings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_NumberofSiblings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NumberofSiblingsjTextField_Firstname8ActionPerformed(evt);
            }
        });

        jLabel258.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel258.setForeground(new java.awt.Color(169, 224, 49));
        jLabel258.setText("BIRTH OF RANK :");

        jComboBox_Birthrank.setBackground(new java.awt.Color(31, 36, 42));
        jComboBox_Birthrank.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox_Birthrank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIRST BORN", "MIDDLE BORN", "LAST BORN", "TWIN", " ", " " }));
        jComboBox_Birthrank.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

        jLabel259.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel259.setForeground(new java.awt.Color(169, 224, 49));
        jLabel259.setText("FAMILY BACKGROUND");

        jButton_SelectImage.setBackground(new java.awt.Color(169, 224, 49));
        jButton_SelectImage.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_SelectImage.setForeground(new java.awt.Color(0, 0, 0));
        jButton_SelectImage.setText("Select Image");
        jButton_SelectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SelectImageActionPerformed(evt);
            }
        });

        jPanel43.setBackground(new java.awt.Color(0, 0, 0));

        Updatebtn.setBackground(new java.awt.Color(0, 0, 0));
        Updatebtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(169, 224, 49));
        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });

        Clearbtn.setBackground(new java.awt.Color(0, 0, 0));
        Clearbtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        Clearbtn.setForeground(new java.awt.Color(169, 224, 49));
        Clearbtn.setText("Clear");
        Clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(Updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jLabelProfileImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));

        jDesktopPane1.setLayer(jLabelProfileImage, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelProfileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(3, Short.MAX_VALUE)))
        );

        Jlabelimg_path.setBackground(new java.awt.Color(169, 224, 49));
        Jlabelimg_path.setFont(new java.awt.Font("Verdana", 1, 5)); // NOI18N
        Jlabelimg_path.setForeground(new java.awt.Color(169, 224, 49));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel259))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel41Layout.createSequentialGroup()
                                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel253, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_YourOccupation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel251, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel257, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_NumberofSiblings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel254)
                                    .addComponent(jTextField_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel258)
                                    .addComponent(jComboBox_Birthrank, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel41Layout.createSequentialGroup()
                                .addComponent(jTextField_FathersName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel252)
                                    .addComponent(jTextField_MothersName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jlabelimg_path, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_SelectImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel41Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel259, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel251)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_FathersName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel252)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_MothersName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel253)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_YourOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel254)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel257)
                        .addGap(4, 4, 4)
                        .addComponent(jTextField_NumberofSiblings, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addComponent(jLabel258)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox_Birthrank, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jlabelimg_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_SelectImage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jPanel42.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 0, 580, 680));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(169, 224, 49));
        jLabel1.setText("FIRST NAME :");
        jPanel42.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 111, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(169, 224, 49));
        jLabel2.setText("PERSONAL INFORMATION");
        jPanel42.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 50));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(169, 224, 49));
        jLabel3.setText("LAST NAME :");
        jPanel42.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(169, 224, 49));
        jLabel5.setText("AGE:");
        jPanel42.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(169, 224, 49));
        jLabel6.setText("PHONE NUMBER:");
        jPanel42.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jTextField_Firstname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Firstname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Firstname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Firstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstnameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 131, 330, 40));

        jTextField_Age.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Age.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AgeActionPerformed(evt);
            }
        });
        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 40));

        jTextField_Phonenumber.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Phonenumber.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Phonenumber.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Phonenumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhonenumberActionPerformed(evt);
            }
        });
        jTextField_Phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhonenumberKeyTyped(evt);
            }
        });
        jPanel42.add(jTextField_Phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 150, 40));

        jComboBox_Address.setBackground(new java.awt.Color(31, 36, 42));
        jComboBox_Address.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox_Address.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MACTAN", "IBO", "SOONG I", "SOONG II", "ENGANO", "ANGASIL", "KAKONSOR", "IBAPO", "KASANTA", " " }));
        jComboBox_Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jPanel42.add(jComboBox_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 160, 40));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(169, 224, 49));
        jLabel8.setText("ADDRESS :");
        jPanel42.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        jTextField_Lastname.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Lastname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Lastname.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Lastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LastnameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 330, 40));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(169, 224, 49));
        jLabel4.setText("MIDDLE NAME :");
        jPanel42.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jTextField_Middlename.setBackground(new java.awt.Color(31, 36, 42));
        jTextField_Middlename.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jTextField_Middlename.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Middlename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jTextField_Middlename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MiddlenameActionPerformed(evt);
            }
        });
        jPanel42.add(jTextField_Middlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 330, 40));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(169, 224, 49));
        jLabel7.setText("DATE OF BIRTH:");
        jPanel42.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jDateChooser_DOB.setBackground(new java.awt.Color(31, 36, 42));
        jDateChooser_DOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jDateChooser_DOB.setForeground(new java.awt.Color(31, 36, 42));
        jPanel42.add(jDateChooser_DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(169, 224, 49));
        jLabel9.setText("GENDER :");
        jPanel42.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, -1, -1));

        jComboBox_Gender.setBackground(new java.awt.Color(31, 36, 42));
        jComboBox_Gender.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jComboBox_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jComboBox_Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 224, 49), 2));
        jPanel42.add(jComboBox_Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, 656, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FathersNamejTextField_Firstname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FathersNamejTextField_Firstname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FathersNamejTextField_Firstname2ActionPerformed

    private void jTextField_MothersNamejTextField_Firstname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MothersNamejTextField_Firstname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MothersNamejTextField_Firstname3ActionPerformed

    private void jTextField_YourOccupationjTextField_Firstname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_YourOccupationjTextField_Firstname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_YourOccupationjTextField_Firstname4ActionPerformed

    private void jTextField_ReligionjTextField_Firstname5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ReligionjTextField_Firstname5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ReligionjTextField_Firstname5ActionPerformed

    private void jTextField_NumberofSiblingsjTextField_Firstname8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NumberofSiblingsjTextField_Firstname8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NumberofSiblingsjTextField_Firstname8ActionPerformed

    private void jButton_SelectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SelectImageActionPerformed
        // TODO add your handling code here:
        //String File;
        /**JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(null);
        File f = fileChooser.getSelectedFile();
        String fileName = f.getAbsolutePath();
        Path.setText(fileName);
        Image getAsolutePath = null;
        ImageIcon icon = new ImageIcon(fileName);
        Image image = icon.getImage().getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_DEFAULT);
        jLabelProfileImage.setIcon(icon);
        jLabelProfileImage.setIcon(ResizeImage(f));**/
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jpg","*.png","*.gif","*.bmp");
        fileChooser.addChoosableFileFilter(filter);
        int result=fileChooser.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            Jlabelimg_path.setText(path);
            jLabelProfileImage.setIcon(ResizeImage(path));
            imgPath = path;
            //cmdRegisterWithImage.setVisible(true);
            //cmdRegister.setVisible(false);
        }else if(result==JFileChooser.CANCEL_OPTION){
            jLabelProfileImage.setIcon(null);
            //cmdRegister.setVisible(true);
            //cmdRegisterWithImage.setVisible(false);
            JOptionPane.showMessageDialog(null, "Select an Image","Barangay System",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton_SelectImageActionPerformed
     public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabelProfileImage.getWidth(), jLabelProfileImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
        }
    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        if(jTextField_Firstname.getText().equals("") || jTextField_Middlename.getText().equals("") || jTextField_Lastname.getText().equals("") || jDateChooser_DOB.getDate().equals("")
            || jTextField_Age.getText().equals("") || jTextField_Phonenumber.getText().equals("") || jTextField_FathersName.getText().equals("") || jTextField_MothersName.getText().equals("") || jTextField_YourOccupation.getText().equals("")
            || jTextField_Religion.getText().equals("") || jTextField_NumberofSiblings.getText().equals("") || jLabelProfileImage.getIcon().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Specified the Required Fields  (  *  )","Barangay System",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String registerUserQuery = "UPDATE `useraccountinfo` SET `Firstname`=?,`Middlename`=?,`Lastname`=?,`Birthdate`=?,`Age`=?,`Phonenumber`=?,`Address`=?,`Gender`=?,`Fathersname`=?,`Mothersname`=?,`Occupation`=?,`Religion`=?,`No.Siblings`=?,`Birthrank`=?,`profilepic`=?";
            int selectedOption = JOptionPane.showConfirmDialog(null, "Are you sure?", "Barangay System",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (selectedOption==JOptionPane.YES_OPTION)
            {
                try{
                    InputStream img = new FileInputStream(new File(imgPath));
                    pst = MyConnection.getConnection().prepareStatement(registerUserQuery);
                    //InputStream is = new FileInputStream(new File(s));
                    pst.setString(1,jTextField_Firstname.getText());
                    pst.setString(2,jTextField_Middlename.getText());
                    pst.setString(3,jTextField_Lastname.getText());
                    pst.setString(4,((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText());
                    pst.setString(5,jTextField_Age.getText());
                    pst.setString(6,jTextField_Phonenumber.getText());
                    pst.setString(7,jComboBox_Address.getSelectedItem().toString());
                    pst.setString(8,jComboBox_Gender.getSelectedItem().toString());
                    pst.setString(9,jTextField_FathersName.getText());
                    pst.setString(10,jTextField_MothersName.getText());
                    pst.setString(11,jTextField_YourOccupation.getText());
                    pst.setString(12,jTextField_Religion.getText());
                    pst.setString(13,jTextField_NumberofSiblings.getText());
                    pst.setString(14,jComboBox_Birthrank.getSelectedItem().toString());
                    pst.setBlob(15,img);
                    pst.executeUpdate();

                }   catch(Exception e){JOptionPane.showMessageDialog(null, e);}
                //con.close();
                JOptionPane.showMessageDialog(null, "User Successfully Registered","Barangay System",JOptionPane.INFORMATION_MESSAGE);
                jTextField_Firstname.getText().equals("");
                jTextField_Middlename.getText().equals("");
                jTextField_Lastname.getText().equals("");
                jDateChooser_DOB.getDate().equals("");
                jTextField_Age.getText().equals("");
                jTextField_Phonenumber.getText().equals("");
                jTextField_FathersName.getText().equals("");
                jTextField_MothersName.getText().equals("");
                jTextField_YourOccupation.getText().equals("");
                jTextField_Religion.getText().equals("");
                jTextField_NumberofSiblings.getText().equals("");
                jLabelProfileImage.getIcon().equals("");
            }

            // TODO add your handling code here:
            //        String registerUserQuery = "UPDATE `residentaccountinfo` SET`Lastname`=?,`Age`=?,`Address`=?,`Phonenumber`=?,`Birthdate`=? WHERE Firstname=?";
            //        String fname = jTextField_Firstname.getText();
            //        String lname = jTextField_Lastname.getText();
            //        String Age = jTextField_Age.getText();
            //        String Address= jComboBox_Address.getSelectedItem().toString();
            //        String Phonenumber= jTextField_Phonenumber.getText();
            //        var Birthdate = ((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText();
            //        try {
                //            ps = MyConnection.getConnection().prepareStatement(registerUserQuery);
                //            ps.setString(6, fname);
                //            ps.setString(1, lname);
                //            ps.setString(2, Age);
                //            ps.setString(3, Address);
                //            ps.setString(4, Phonenumber);
                //            ps.setString(5, Birthdate);
                //            ps.executeUpdate();
                //            JOptionPane.showMessageDialog(null,"Updated Successfully!");
                //
                //        }catch (SQLException ex) {
                //            JOptionPane.showMessageDialog(null, ex);
                //        }
            //showTable();
        }
    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void ClearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbtnActionPerformed
        // TODO add your handling code here:
        jTextField_Firstname.setText(null);
        jTextField_Middlename.setText(null);
        jTextField_Lastname.setText(null);
        jDateChooser_DOB.setDate(null);
        jTextField_Age.setText(null);
        jTextField_Phonenumber.setText(null);
        jTextField_FathersName.setText(null);
        jTextField_MothersName.setText(null);
        jTextField_Religion.setText(null);
        jTextField_NumberofSiblings.setText(null);
        jLabelProfileImage.setIcon(null);
        jTextField_YourOccupation.setText(null);
    }//GEN-LAST:event_ClearbtnActionPerformed

    private void jTextField_FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstnameActionPerformed

    private void jTextField_AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AgeActionPerformed

    private void jTextField_PhonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhonenumberActionPerformed

    private void jTextField_PhonenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhonenumberKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhonenumberKeyTyped

    private void jTextField_LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LastnameActionPerformed

    private void jTextField_MiddlenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MiddlenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MiddlenameActionPerformed

    private void jTextField_AgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AgeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearbtn;
    private javax.swing.JLabel Jlabelimg_path;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JButton jButton_SelectImage;
    private javax.swing.JComboBox<String> jComboBox_Address;
    private javax.swing.JComboBox<String> jComboBox_Birthrank;
    private javax.swing.JComboBox<String> jComboBox_Gender;
    private com.toedter.calendar.JDateChooser jDateChooser_DOB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel251;
    private javax.swing.JLabel jLabel252;
    private javax.swing.JLabel jLabel253;
    private javax.swing.JLabel jLabel254;
    private javax.swing.JLabel jLabel257;
    private javax.swing.JLabel jLabel258;
    private javax.swing.JLabel jLabel259;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelProfileImage;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_FathersName;
    private javax.swing.JTextField jTextField_Firstname;
    private javax.swing.JTextField jTextField_Lastname;
    private javax.swing.JTextField jTextField_Middlename;
    private javax.swing.JTextField jTextField_MothersName;
    private javax.swing.JTextField jTextField_NumberofSiblings;
    private javax.swing.JTextField jTextField_Phonenumber;
    private javax.swing.JTextField jTextField_Religion;
    private javax.swing.JTextField jTextField_YourOccupation;
    // End of variables declaration//GEN-END:variables
}
